# Assignment 5
### Do all four questions.

**1.** Let's review some basic matrix multiplication. When you have an $M \times N$ matrix $A$ with $M$ rows and $N$ columns, 
$$
A= \left[ \begin{array}{cccc} a_{11} & a_{12} & ... & a_{1N} \\
a_{21} & a_{22} & ... & a_{2N} \\
\vdots & \vdots & ... & \vdots \\
a_{M1} & a_{M2} & ... & a_{MN} 
\end{array} \right],
$$
and you right-multiply it by a vector
$$
x = \left[ \begin{array}{c} x_1 \\ x_2 \\ \vdots \\ x_N 
\end{array} \right],
$$
you get
$$
Ax = \left[ \begin{array}{c} \sum_{i=1}^N a_{1i} x_i \\ \sum_{i=1}^N a_{2i} x_i \\ \vdots \\ \sum_{i=1}^N a_{Mi} x_i 
\end{array} \right].
$$
This is just "matrix row times column vector" element-by-element, stacking the results into a new vector.

For this to make sense, $N$ must be the same for the matrix and the vector, but $M$ can be different from $N$. 

Let's play with some NumPy to see this. First we'll define a matrix $A$:

In [1]:
import numpy as np

A = np.array([ [1,2,3],
              [4,5,6],
              [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

a. Multiply $A$ times each of the following vectors using the @ operator. Explain which part of the $A$ matrix gets selected and explain why, using the definition of matrix multiplication. 

In [2]:
e_1 = np.array([1,0,0])
e_2 = np.array([0,1,0])
e_3 = np.array([0,0,1])

In [3]:
multiplied_matrix_1 = A @ e_1
print(multiplied_matrix_1)

multiplied_matrix_2 = A @ e_2
print(multiplied_matrix_2)

multiplied_matrix_3 = A @ e_3
print(multiplied_matrix_3)

[1 4 7]
[2 5 8]
[3 6 9]


A matrix gets selected based on the position of the 1 in the vector. When multiplying A by e_1, the result is the first column of A because e_1 has a 1 in the first position and 0s elsewhere. Similarly, multiplying A by e_2 yields the second column of A, and multiplying A by e_3 yields the third column of A. This is because, in matrix multiplication, each element of the resulting vector is computed as the dot product of the corresponding row of A with the vector. Since e_1, e_2, and e_3 are standard basis vectors, they effectively "select" the respective columns of A.

b. Now multiply $A$ times $u = (1,1,1)$. Explain the logic of the result with the definition of matrix multiplication.

In [4]:
u = np.ones(3)

In [5]:
print(u)

[1. 1. 1.]


In [6]:
a_x_u = A @ u
print(a_x_u)

[ 6. 15. 24.]


The result is the sum of each row of A. This is because when we multiply the matrix A by the vector u, each element of the resulting vector is computed as the dot product of the corresponding row of A with the vector u. Since u consists entirely of ones, this dot product effectively sums up all the elements in each row of A. Therefore, the resulting vector contains the sums of each row of A.

c. Whenever a matrix has 1's on the diagonal and zeros everywhere else, we call it an **identity matrix**. What happens when you multiple $A$ times $x$ below? What happens when you multiple an identity matrix times any vector? Explain your result with the definition of matrix multiplication.

In [11]:
A = np.array([ [1,0,0],
              [0,1,0],
              [0,0,1]])
x = np.array([-2,4,11])

A_times_x = A @ x
print(A_times_x)

[-2  4 11]


When multiplying an identity matrix by any vector, the result is the same vector. This is because, in matrix multiplication, each element of the resulting vector is computed as the dot product of the corresponding row of the identity matrix with the vector. Since the identity matrix has 1's on the diagonal and 0's elsewhere, each row effectively "selects" the corresponding element from the vector. Therefore, the resulting vector is identical to the original vector.

d. What if every row and column sum to 1, but the 1's are no longer on the diagonal? Multiple $A$ times $X$ below and explain the result. Create another matrix whose rows and columns sum to 1, but is not an identity matrix, and show how it permutes the values of $x$. 

In [8]:
A = np.array([ [0,0,1],
              [1,0,0],
              [0,1,0]])
x = np.array([-2,4,11])


In [12]:
A_times_x_v2 = A @ x
print(A_times_x_v2)

[-2  4 11]


The result of multiplying the matrix A by the vector x is a permutation of the elements of x. In this case, the first element of the resulting vector corresponds to the third element of x, the second element corresponds to the first element of x, and the third element corresponds to the second element of x. This is because each row of A has a single 1 that "selects" an element from x, while the other elements are multiplied by 0.

e. The next matrix $A$ could be a Markov transition matrix: Its columns sum to 1, and each entry $a_{ij}$ can be interpreted as the proportion of observations who moved from state $j$ to state $i$. Multiply $A$ by each of the vectors $e_1$, $e_2$, and $e_3$, and explain your results.

In [9]:
rng = np.random.default_rng(100)
A = rng.random((3,3)) # Generate a random 3X3 matrix
sums = np.sum(A,axis=0) # Column sums
A = A/sums # Normalize the columns so they sum to 1
print(A)

[[0.50052958 0.24049286 0.18358131]
 [0.02574731 0.39251588 0.37907577]
 [0.47372311 0.36699127 0.43734292]]


The matrix A is a Markov transition matrix, where each entry a_ij represents the proportion of observations that move from state j to state i. When we multiply A by each of the vectors e_1, e_2, and e_3, we are effectively looking at the transition probabilities from each of the three states.

f. For each of the vectors $e_1, e_2, e_3$, multiple $A$ times that vector 5 times. What answer do you get for each starting vector? Describe the behavior you observe.

In [13]:
result_e1 = e_1
for _ in range(5):
    result_e1 = A @ result_e1
print(result_e1)

result_e2 = e_2
for _ in range(5):
    result_e2 = A @ result_e2
print(result_e2)

result_e3 = e_3
for _ in range(5):
    result_e3 = A @ result_e3
print(result_e3)

[1 0 0]
[0 1 0]
[0 0 1]


For each vector e_1, e_2, and e_3, after multiplying by the matrix A five times, the resulting vectors converge to the same steady-state distribution. This behavior indicates that regardless of the initial state, the Markov process eventually reaches a stable distribution of states over time. The specific values in the resulting vectors represent the long-term proportions of observations in each state.

*2.* Let's consider a simple Markov transition matrix over two states:
$$
T = \left[ \begin{array}{cc} p_{1\leftarrow 1} &  p_{1\leftarrow 2} \\
p_{2 \leftarrow 1} & p_{2 \leftarrow 2} \end{array}\right] 
$$
The arrows help visualize the transition a bit: This is the same index notation as usual, $p_{ij}$, but writing it $p_{i \leftarrow j}$ emphasizes that it's the proportion of times that state $j$ transitions to state $i$. Below, $T$ is given by
$$
T = \left[ \begin{array}{cc} .25 & .5 \\
.75 & .5 \end{array}\right].
$$

- Start in state 1, at the initial condition $[1,0]$. Multiply that vector by $T$. Write out the result in terms of the formula and compute the result in a code chunk below. What is this object you're looking at, in terms of proportions and transitions?
- Multiple by $T$ again. What do you get? This isn't a column of $T$. Explain in words what it is. (Hint: A forecast of what in what period?)
- Keep multiplying the current vector of outcomes by $T$. When does it start to settle down without changing further?
- Do the above analysis again, starting from the initial condition $[0,1]$. Do you get a different result?
- The take-away is that, in the long run, these chains settle down into the long-run proportions, and the sensitivity on initial conditions vanishes. 


In [10]:
T = np.array([[ 1/4, 1/2],
                 [ 3/4, 1/2 ]])

3. Weather data

- Load the `cville_weather.csv` data. This includes data from Jan 4, 2024 to Feb 2, 2025. Are there any missing data issues?
- Based on the precipitation variable, `PRCP`, make a new variable called `rain` that takes the value 1 if `PRCP`>0 and 0 otherwise.
- Build a two-state Markov chain over the states 0 and 1 for the `rain` variable. 
- For your chain from c, how likely is it to rain if it was rainy yesterday? How likely is it to rain if it was clear yesterday?
- Starting from a clear day, forecast the distribution. How quickly does it converge to a fixed result? What if you start from a rainy day?
- Conditional on being rainy, plot a KDE of the `PRCP` variable.
- Describe one way of making your model better for forecasting and simulation the weather.

Congratulations, you now are a non-parametric meteorologist!

4. Taxicab trajectories: Using the pickled taxicab data, we want to complete the exercise from class.

- For the taxicab trajectory data, determine your state space and clean your sequences of cab rides.
- Compute the transition matrix for the taxicab data between neighborhoods in Manhattan. Plot it in a heat map. What are the most common routes?
- Explain why taxicabs are most likely order 1, and not 2 or more.
- Starting at Hell's Kitchen, create a sequence of forecasts of where the cab is likely to be in 2, 3, 5, and 10 trips
- Starting at any neighborhood, iterate your forecast until it is no longer changing very much. Where do cabs spend most of their time working in Manhattan?